version: "3.8"

services:
  db:
    image: postgres:12-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./teste.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "7000:5432"

  java:
    build: ./java/
    networks:
      - default

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/src:/usr/src/app/src
    networks:
      - default

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8010:80"
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  pgdata: 
